return {
	descriptions={
        Joker={
            j_slightjokers_blue_card={
                name="蓝牌",
                text={
                    "当跳过任一{C:attention}补充包{}时",
                    "这张小丑牌获得{C:chips}+#1#{}筹码",
                    "{C:inactive}（当前为{C:chips}+#2#{C:inactive}筹码）",
                },
            },
            j_slightjokers_century_egg={
                name="皮蛋",
                text={
                    "拥有此小丑牌时",
                    "小丑牌槽位{C:dark_edition}+#1#{}",
                    "在每回合结束时获得",
                    "本卡{C:attention}出售价值{}的资金",
                },
            },
            j_slightjokers_chinese_chef={
                name="中华厨师",
                text={
                    "在离开商店时",
                    "随机生成一张{C:attention}皮蛋{}",
                    "{C:attention}粽子{}、{C:attention}拉面{}或{C:attention}黑龟豆",
                    "{C:inactive}（必须有空间）",
                },
            },
            j_slightjokers_evil_astronaut={
                name="邪恶宇航员",
                text={
                    "所有{C:attention}牌型{}在本赛局中",
                    "{C:attention}打出过{}次数双倍计入",
                    "有{C:green}#1#/#2#{}的几率",
                    "升级打出的{C:attention}牌型等级{}",
                    "{s:0.6}（例:出一次高牌将统计为打出过两次）",
                },
            },
            j_slightjokers_exiled_joker={
                name="流亡小丑",
                text={
                    "每当添加{C:attention}卡牌{}",
                    "到你的牌组中时",
                    "使添加牌获得{X:mult,C:white}X#1#{}倍率",
                },
            },
            j_slightjokers_lava_erupt={
                name="迸射",
                text={
                    "打出原先不计分的牌时",
                    "临时增强它们为{C:attention}石头牌",
                    "计分结束后复原",
                },
            },
            j_slightjokers_pe_student={
                name="体育生",
                text={
                    "如果打出的牌中包含",
                    "{C:attention}顺子{}",
                    "这张小丑获得{X:chips,C:white} X#1# {}筹码",
                    "{C:inactive}（当前为{X:chips,C:white} X#2# {C:inactive}筹码）",
                },
            },
            j_slightjokers_polar_climber={
                name="极地攀登者",
                text={
                    "在每回合结束时",
                    "留在手牌中的牌",
                    "获得{X:chips,C:white} X#1# {}筹码",
                },
            },
            j_slightjokers_sam_club={
                name="山姆会员",
                text={
                    "商店內",
                    "卡牌槽位{C:attention}+#1#{}",
                    "启用{C:attention}通货膨胀",
                },
            },
            j_slightjokers_world_end={
                name="世界末日",
                text={
                    "每张消耗牌槽位中的{C:planet}星球牌{}",
                    "会给予{C:chips}+#1#{}筹码、{C:mult}+#2#{}倍率",
                    "和{X:mult,C:white} X#3# {}倍率",
                },
            },
            j_slightjokers_ignis_fatuus={
                name="鬼火",
                text={
                    "每{C:attention}购买{}一张牌",
                    "这张小丑牌获得{X:chips,C:white}X#1#{}筹码",
                    "{C:attention}Boss盲注{}被击败时重置倍率",
                    "{C:inactive}（当前为{X:chips,C:white}X#2#{C:inactive}筹码）",
                },
            },
            j_slightjokers_minotaur={
                name="牛头人",
                text={
                    "{C:attention}Boss盲注{}开始时",
                    "这张小丑牌获得{C:chips}+#1#{}筹码",
                    "{C:inactive}（当前为{C:chips}+#2#{C:inactive}筹码）",
                },
            },
            j_slightjokers_mysterious_nebula={
                name="神秘星云",
                text={
                    "将{C:attention}牌型{}在本赛局内",
                    "被{C:attention}打出过{}的次数",
                    "与{C:attention}牌型等级{}数都",
                    "添加至倍率",
                },
            },
            j_slightjokers_old_phone={
                name="老旧手机",
                text={
                    "重新触发",
                    "所有打出的",
                    "{C:dark_edition}#1#{}、{C:dark_edition}#2#{}、{C:dark_edition}#3#{}",
                    "和点数为{C:attention}#4#{}、{C:attention}#5#{}的牌",
                    "{s:0.8}每回合都会重新拨号",
                },
            },
            j_slightjokers_rice_dumpling={
                name="粽子",
                text={
                    "回合结束时",
                    "每拥有{C:money}$5{}",
                    "可以额外获得{C:money}$#1#{}的{C:attention}利息{}",
                    "在进入商店时减{C:money}$#2#{}",
                },
            },
            j_slightjokers_square_family={
                name="方型家族",
                text={
                    "打开任一{C:attention}小丑包{}时",
                    "其中随机牌将{C:attention}变方{}",
                    "每张{C:blue}方型{}的小丑牌",
                    "会给予{X:chips,C:white} X#1# {}筹码",
                },
            },
            j_slightjokers_great_moment={
                name="美好时光",
                text={
                    "打出的{C:attention}第一张{}卡牌",
                    "在计分时",
                    "会平衡{C:blue}筹码{}和{C:red}倍率{}",
                },
            },
            j_slightjokers_private_bank={
                name="私行贵宾卡",
                text={
                    "商店内",
                    "各种槽位{C:attention}+#1#{}",
                },
            },
            j_slightjokers_cloistered_joker={
                name="隐居小丑",
                text={
                    "在任一{C:attention}补充包{}中时",
                    "每使用一张{C:attention}消耗牌{}",
                    "这张小丑牌获得{C:mult}+#1#{}倍率",
                    "{C:inactive}（当前为{C:mult}+#2#{C:inactive}倍率）",
                },
            },
            j_slightjokers_lightning_summit={
                name="闪电之峰",
                text={
                    "每一个剩余的",
                    "{C:attention}出牌{}次数",
                    "{C:mult}+#1#{}倍率",
                },
            },
        },
        Back={
            b_slightjokers_curtain={
                name="帷幕牌组",
                text={
                    "开局时拥有",
                    "{C:attention,T:v_magic_trick}魔术{}优惠券",
                    "添加的游戏牌将被{C:attention}摧毁",
                    "并使牌组中所有卡牌",
                    "获得相同点数的{C:chips}基础筹码",
                },
            },
        },
        Sleeve={
            sleeve_slightjokers_curtain={
                name="帷幕牌套",
                text={
                    "开局时拥有",
                    "{C:attention,T:v_magic_trick}魔术{}优惠券",
                    "添加的游戏牌将被{C:attention}摧毁",
                    "并使牌组中所有卡牌",
                    "获得相同点数的{C:chips}基础筹码",
                },
            },
            sleeve_slightjokers_curtain_alt={
                name="帷幕牌套",
                text={
                    "开局时拥有",
                    "{C:attention,T:v_illusion}幻象{}优惠券",
                },
            },
        },
        Other={
            slightjokers_ramen={
                name = '拉面',
                text = {
                    "{X:mult,C:white}X2{}倍率",
                    "每{C:attention}弃掉一张牌{}",
                    "失去{X:mult,C:white}X0.01{}倍率",
                },
            },
            slightjokers_inflation={
                name = '通货膨胀',
                text = {
                    "每次购买后",
                    "所有物价",
                    "将会上涨{C:money}$1{}",
                },
            },
        }
    },
    misc = {
        dictionary = {
            slightjokers_erupt_solidify="凝固",
            slightjokers_square="方型",
        },
        v_dictionary={
            slightjokers_worldend="+#1#筹码 +#2#倍率 X#3#倍率",
            slightjokers_ricedumpling="-$#1#",
        }
    }
}
